apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-eu-central
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
  - service-patch.yaml
