package ingest

import "testing"

func TestLooksGenerated(t *testing.T) {
	cases := []struct {
		name string
		body string
		want bool
	}{
		{"helm render header", "# Generated by helm template - do not edit\nfoo: bar\n", true},
		{"do-not-edit banner", "// Code generated by protoc. DO NOT EDIT.\n", true},
		{"xml comment", "<!-- @generated -->\n<config/>\n", true},
		{"plain config", "replicaCount: 2\nimage:\n  tag: \"1.0\"\n", false},
		{"marker only in a value, not a comment", "note: this file is generated nightly\n", false},
		{"marker below the header window", header20 + "# generated by tool\n", false},
	}
	for _, tc := range cases {
		if got := looksGenerated([]byte(tc.body)); got != tc.want {
			t.Errorf("%s: looksGenerated = %v, want %v", tc.name, got, tc.want)
		}
	}
}

// header20 is 20 non-comment lines, pushing anything after it out of the header
// window looksGenerated inspects.
var header20 = func() string {
	s := ""
	for i := 0; i < 20; i++ {
		s += "key: value\n"
	}
	return s
}()
