package ingest

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/abhijeet-oxide/configer/backend/internal/parsers"
	"github.com/abhijeet-oxide/configer/backend/internal/plugin"
	"github.com/abhijeet-oxide/configer/backend/internal/project"
	"github.com/abhijeet-oxide/configer/backend/internal/recognizers"
)

// A file the scan passes over says WHY. The reported case: Flux writes
// "This manifest was generated by flux. DO NOT EDIT." at the top of every
// gotk-components.yaml, so Configer leaves it alone - correctly, because the
// next flux bootstrap overwrites whatever anyone edits there. What was missing
// was any way for the user to learn that; the answer was a bare path under a
// key called "skipped", which reads as a fault rather than a decision.
func TestSkippedFilesCarryTheirReason(t *testing.T) {
	root := t.TempDir()
	write := func(rel, body string) {
		full := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("clusters/wnv7a0/flux-system/gotk-components.yaml",
		"---\n# This manifest was generated by flux. DO NOT EDIT.\n# See: https://github.com/fluxcd/flux2\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: flux-system\n")
	write("clusters/wnv7a0/values.yaml", "app:\n  port: 8080\n")
	write("secrets/creds.yaml", "token: hunter2\n")

	reg := plugin.NewRegistry()
	parsers.Register(reg)
	recognizers.Register(reg)
	res, err := Scan(root, reg, project.Ignore{Files: []string{"secrets/**"}})
	if err != nil {
		t.Fatal(err)
	}

	by := map[string]SkipReason{}
	for _, s := range res.Skipped {
		by[s.File] = s.Reason
	}
	if got := by["clusters/wnv7a0/flux-system/gotk-components.yaml"]; got != SkipGenerated {
		t.Errorf("a generated manifest = %q, want %q", got, SkipGenerated)
	}
	if got := by["secrets/creds.yaml"]; got != SkipIgnored {
		t.Errorf("an ignored file = %q, want %q", got, SkipIgnored)
	}
	// And the ordinary file is scanned, not passed over.
	if _, passed := by["clusters/wnv7a0/values.yaml"]; passed {
		t.Error("a plain configuration file must not be passed over")
	}
	if res.Total == 0 {
		t.Error("the plain configuration file yielded no candidates")
	}
}
