// Package ingest scans a repository working tree, detects configuration files
// via the registered parser plugins, and extracts candidate parameters. Files
// matching ignore globs (or living under .configer or .git) are skipped.
package ingest

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/abhijeet-oxide/configer/backend/internal/plugin"
	"github.com/abhijeet-oxide/configer/backend/internal/project"
)

// FileResult is the extraction outcome for one source file.
type FileResult struct {
	File       string             `json:"file"`
	Format     string             `json:"format"`
	Parser     string             `json:"parser"`
	Candidates []plugin.Candidate `json:"candidates"`
	Error      string             `json:"error,omitempty"`
}

// ScanResult is the full result of scanning a repository.
type ScanResult struct {
	Root    string       `json:"root"`
	Files   []FileResult `json:"files"`
	Skipped []string     `json:"skipped"`
	Total   int          `json:"total"` // total candidate parameters found
}

var alwaysSkip = map[string]bool{".git": true, ".configer": true, "node_modules": true}

// Scan walks root, applying ignore rules, and extracts candidate parameters.
func Scan(root string, reg *plugin.Registry, ignore project.Ignore) (ScanResult, error) {
	res := ScanResult{Root: root}

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, path)
		// Normalize to forward slashes so downstream matching (instance-folder
		// prefixes, bindings, ignore globs) is identical on Windows and Unix.
		// Without this, a Windows "instances\prod\values.yaml" never matches an
		// "instances/prod/" folder prefix and every file wrongly falls to the
		// shared layer (0 instances detected).
		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			if alwaysSkip[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if matchesIgnore(rel, ignore.Files) {
			res.Skipped = append(res.Skipped, rel)
			return nil
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil // skip unreadable files
		}
		// A file a generator emitted (a committed `helm template` render, a
		// codegen output) is a copy of config that lives elsewhere: managing it
		// creates a second source of truth that drifts. Generators stamp a
		// "do not edit / generated by" header; honor it, whatever the directory
		// is named, so this is not hardcoded to any one convention.
		if looksGenerated(content) {
			res.Skipped = append(res.Skipped, rel)
			return nil
		}
		parser, perr := reg.ParserFor(rel, content)
		if perr != nil {
			return nil // not a recognized config file
		}
		fr := FileResult{File: rel, Parser: parser.Manifest().ID}
		cands, exErr := parser.Extract(rel, content)
		if exErr != nil {
			fr.Error = exErr.Error()
		} else {
			// drop ignored parameters (by path)
			for _, c := range cands {
				if matchesIgnore(c.Path, ignore.Parameters) || contains(ignore.Parameters, c.Path) {
					continue
				}
				fr.Candidates = append(fr.Candidates, c)
				fr.Format = c.Format
			}
			res.Total += len(fr.Candidates)
		}
		res.Files = append(res.Files, fr)
		return nil
	})
	return res, err
}

// generatedMarkers are case-insensitive phrases generators stamp into a header
// comment. Kept deliberately narrow so they never trip on a legitimate value.
var generatedMarkers = []string{
	"do not edit", "@generated", "code generated", "generated by",
	"autogenerated", "auto-generated", "this file is generated",
}

// looksGenerated reports whether the file's leading comment header marks it as
// generated output. It inspects only comment lines in the first 20 lines, so a
// marker phrase buried in a real config value never causes a false skip.
func looksGenerated(content []byte) bool {
	head := content
	if len(head) > 4096 {
		head = head[:4096]
	}
	lines := strings.SplitN(string(head), "\n", 21)
	if len(lines) > 20 {
		lines = lines[:20]
	}
	for _, ln := range lines {
		t := strings.TrimSpace(ln)
		// Only a comment line counts (YAML/#, JSON-with-comments or XML //, XML <!--).
		if !strings.HasPrefix(t, "#") && !strings.HasPrefix(t, "//") && !strings.HasPrefix(t, "<!--") {
			continue
		}
		low := strings.ToLower(t)
		for _, m := range generatedMarkers {
			if strings.Contains(low, m) {
				return true
			}
		}
	}
	return false
}

func matchesIgnore(rel string, patterns []string) bool {
	rel = filepath.ToSlash(rel)
	for _, p := range patterns {
		if ok, _ := filepath.Match(p, rel); ok {
			return true
		}
		// support suffix globs like "**/*.tmp"
		if strings.HasPrefix(p, "**/") {
			if ok, _ := filepath.Match(strings.TrimPrefix(p, "**/"), filepath.Base(rel)); ok {
				return true
			}
		}
	}
	return false
}

func contains(ss []string, s string) bool {
	for _, x := range ss {
		if x == s {
			return true
		}
	}
	return false
}
