package discovery

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/abhijeet-oxide/configer/backend/internal/model"
	"github.com/abhijeet-oxide/configer/backend/internal/project"
)

// writeTree writes a map of relative path -> content under root.
func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, body := range files {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// A deliberately messy Helm umbrella exercises the four real-world hardening
// behaviors together: identity-keyed lists, dropped anchor mirrors, subchart
// canonicalization, and skipped generated output.
func messyFixture(t *testing.T) Result {
	t.Helper()
	root := t.TempDir()
	writeTree(t, root, map[string]string{
		"Chart.yaml": "apiVersion: v2\nname: umbrella\nversion: 1.0.0\n",
		"values.yaml": `global:
  domain: shop.example.com
commonProbes: &probes
  path: /healthz
api:
  replicaCount: 2
  probes: *probes
  ingress:
    host: "api.{{ .Values.global.domain }}"
  env:
    - name: LOG_LEVEL
      value: info
    - name: DEBUG
      value: "false"
worker:
  replicaCount: 3
  probes: *probes
`,
		"charts/api/Chart.yaml":       "apiVersion: v2\nname: api\nversion: 0.1.0\n",
		"charts/api/values.yaml":      "replicaCount: 1\nimage:\n  tag: \"1.0.0\"\n",
		"charts/worker/Chart.yaml":    "apiVersion: v2\nname: worker\nversion: 0.1.0\n",
		"charts/worker/values.yaml":   "replicaCount: 1\nimage:\n  tag: \"1.0.0\"\n",
		"environments/dev/values.yaml":  "api:\n  replicaCount: 1\n",
		"environments/prod/values.yaml": "api:\n  replicaCount: 5\n",
		"rendered/out.yaml":             "# Generated by helm template - do not edit\nfoo: bar\n",
	})
	res, err := Discover(root, registry(), project.Ignore{})
	if err != nil {
		t.Fatal(err)
	}
	return res
}

// Step 1 (identity lists): a list of {name,value} maps becomes one parameter per
// entry, keyed by the identity field, which survives reordering. The identity
// field itself is not a parameter, and every entry is captured (not just [0]).
func TestMessyIdentityKeyedLists(t *testing.T) {
	byName := paramsByName(messyFixture(t))

	for _, want := range []string{"api.env.LOG_LEVEL.value", "api.env.DEBUG.value"} {
		p, ok := byName[want]
		if !ok {
			t.Fatalf("missing keyed list parameter %q; have %v", want, keys(byName))
		}
		if got := p.Bindings[0].Path; !strings.Contains(got, "[name=") {
			t.Errorf("%s binding path %q is not identity-keyed", want, got)
		}
	}
	// The identity field is a selector, never its own positional parameter.
	if _, ok := byName["api.env.name"]; ok {
		t.Error("identity field api.env.name should not be a parameter")
	}
	for n := range byName {
		if strings.Contains(n, "env[0]") || strings.Contains(n, "env.0") {
			t.Errorf("positional list parameter leaked: %q", n)
		}
	}
}

// Step 4 (anchors): an aliased block is managed once at its definition; the
// alias mirror sites are dropped, so the same setting is not counted twice.
func TestMessyAnchorMirrorsDropped(t *testing.T) {
	byName := paramsByName(messyFixture(t))
	if _, ok := byName["commonProbes.path"]; !ok {
		t.Errorf("anchor definition commonProbes.path should be kept; have %v", keys(byName))
	}
	if _, ok := byName["api.probes.path"]; ok {
		t.Error("alias mirror api.probes.path should be dropped")
	}
	if _, ok := byName["worker.probes.path"]; ok {
		t.Error("alias mirror worker.probes.path should be dropped")
	}
}

// Step 2 (subchart canonicalization): a subchart default unifies with the
// aliased override into ONE layered parameter, and sibling subcharts are not
// over-merged (api's replicaCount is not worker's).
func TestMessySubchartCanonicalization(t *testing.T) {
	byName := paramsByName(messyFixture(t))

	api, ok := byName["api.replicaCount"]
	if !ok {
		t.Fatalf("api.replicaCount missing; have %v", keys(byName))
	}
	if !hasChartDefault(api) {
		t.Errorf("api.replicaCount should carry a chart-default binding: %+v", api.Bindings)
	}
	// instance + base + chart-default all fold into the one parameter.
	if len(api.Bindings) < 3 {
		t.Errorf("api.replicaCount should unify layers, got %d bindings", len(api.Bindings))
	}
	if _, ok := byName["worker.replicaCount"]; !ok {
		t.Error("worker.replicaCount should stay a distinct parameter (not merged with api's)")
	}
	// The bare subchart name must not leak as its own row.
	if _, ok := byName["replicaCount"]; ok {
		t.Error("bare subchart 'replicaCount' should be re-scoped under its alias")
	}
	// api and worker image.tag share a leaf but are different settings.
	if _, a := byName["api.image.tag"]; !a {
		t.Error("api.image.tag missing")
	}
	if _, w := byName["worker.image.tag"]; !w {
		t.Error("worker.image.tag missing (over-merged with api's?)")
	}
}

// Step 1 (generated output): a file stamped as generated is skipped, so its
// values never become a second, drifting source of truth.
func TestMessyGeneratedFileSkipped(t *testing.T) {
	byName := paramsByName(messyFixture(t))
	if _, ok := byName["foo"]; ok {
		t.Error("value from a generated file was ingested; it should be skipped")
	}
}

// Step 3 (template kind): a template expression is recognized so the grid can
// mark the cell read-only and the write path can refuse to clobber it.
func TestTemplateExpressionDetection(t *testing.T) {
	cases := map[any]bool{
		"api.{{ .Values.global.domain }}": true,
		"{{ .Release.Name }}-db":          true,
		"${DB_HOST}":                      true,
		"plain-hostname":                  false,
		"8080":                            false,
		8080:                             false,
		true:                             false,
	}
	for v, want := range cases {
		if got := model.IsTemplateExpression(v); got != want {
			t.Errorf("IsTemplateExpression(%v) = %v, want %v", v, got, want)
		}
	}
}
