package recognizers

import (
	"strings"

	"github.com/abhijeet-oxide/configer/backend/internal/plugin"
)

// Flux recognizes the manifests `flux bootstrap` writes into a cluster path.
//
// These are the controllers Flux runs, rendered by the Flux CLI and committed
// so the cluster can install itself from Git. Editing one DOES work - Flux
// applies whatever is in the repository - but only until the next bootstrap or
// upgrade, which regenerates the file from the CLI's own manifests and drops
// the change with no warning. Flux's answer is a patch in the kustomization
// beside it, which bootstrap leaves alone.
type Flux struct{}

func (Flux) Manifest() plugin.Manifest {
	return plugin.Manifest{
		ID: "flux", Name: "Flux bootstrap", Version: "1", Kind: plugin.KindRecognizer,
		Description: "Recognizes the component and sync manifests flux bootstrap writes.",
		Icon:        "cluster", Category: "GitOps",
	}
}

func (Flux) Recognize(path string, content []byte) (plugin.Origin, bool) {
	base := baseOf(path)
	named := strings.HasPrefix(base, "gotk-") && strings.HasSuffix(base, ".yaml")
	if !named && !strings.Contains(commentLines(content), "generated by flux") {
		return plugin.Origin{}, false
	}
	return plugin.Origin{
		ID:          "flux",
		Name:        "flux bootstrap",
		Regenerates: "flux bootstrap",
		Note: "Flux applies whatever is in this file, so an edit here does reach the cluster - " +
			"until the next bootstrap or upgrade regenerates the file and drops it.",
		Instead: "To make the same change stick, put it in the patches: block of the kustomization.yaml " +
			"beside this file; bootstrap leaves that alone and kustomize applies it on top.",
		Docs: "https://fluxcd.io/flux/installation/configuration/vertical-scaling/",
	}, true
}
