package recognizers

import (
	"strings"

	"github.com/abhijeet-oxide/configer/backend/internal/plugin"
)

// markers are the phrases generators stamp into a header comment. Kept
// deliberately narrow so they never trip on a legitimate value, and checked
// only against comment lines near the top of a file.
var markers = []string{
	"do not edit", "@generated", "code generated", "generated by",
	"autogenerated", "auto-generated", "this file is generated",
}

// Generic is the fallback: a file that says it is generated, by something
// Configer does not recognize. It is registered last, so a named tool always
// gets to answer first with its own specifics.
type Generic struct{}

func (Generic) Manifest() plugin.Manifest {
	return plugin.Manifest{
		ID: "generated-banner", Name: "Generated-file banner", Version: "1", Kind: plugin.KindRecognizer,
		Description: `Recognizes any file whose header says it is generated ("do not edit", "@generated").`,
		Icon:        "file", Category: "General",
	}
}

func (Generic) Recognize(_ string, content []byte) (plugin.Origin, bool) {
	c := commentLines(content)
	for _, m := range markers {
		if strings.Contains(c, m) {
			return plugin.Origin{
				ID:   "generated-banner",
				Name: "a generator",
				Note: "This file's own header says it was generated and should not be edited, " +
					"so whatever wrote it is expected to write it again.",
				Instead: "Manage the input that generator reads, so the change survives the next run.",
			}, true
		}
	}
	return plugin.Origin{}, false
}
