package recognizers

import (
	"strings"

	"github.com/abhijeet-oxide/configer/backend/internal/plugin"
)

// Helm recognizes committed `helm template` output: a chart rendered to plain
// manifests. The tunable values live in the chart's values.yaml, which Configer
// manages happily; the render is a copy of them.
type Helm struct{}

func (Helm) Manifest() plugin.Manifest {
	return plugin.Manifest{
		ID: "helm-template", Name: "helm template", Version: "1", Kind: plugin.KindRecognizer,
		Description: "Recognizes manifests rendered from a Helm chart.",
		Icon:        "package", Category: "Kubernetes",
	}
}

func (Helm) Recognize(_ string, content []byte) (plugin.Origin, bool) {
	c := commentLines(content)
	if !strings.Contains(c, "helm template") && !strings.Contains(c, "generated by helm") {
		return plugin.Origin{}, false
	}
	return plugin.Origin{
		ID:          "helm-template",
		Name:        "helm template",
		Regenerates: "helm template",
		Note:        "Re-rendering the chart writes over this file, so an edit here lasts until the next render.",
		Instead:     "The same settings live in the chart's values.yaml, which Configer can manage directly.",
	}, true
}
