package recognizers

import (
	"strings"

	"github.com/abhijeet-oxide/configer/backend/internal/plugin"
)

// Kpt recognizes output written by a kpt function pipeline.
type Kpt struct{}

func (Kpt) Manifest() plugin.Manifest {
	return plugin.Manifest{
		ID: "kpt", Name: "kpt render", Version: "1", Kind: plugin.KindRecognizer,
		Description: "Recognizes resources written by a kpt function pipeline.",
		Icon:        "package", Category: "Kubernetes",
	}
}

func (Kpt) Recognize(_ string, content []byte) (plugin.Origin, bool) {
	c := commentLines(content)
	if !strings.Contains(c, "kpt fn") && !strings.Contains(c, "generated by kpt") {
		return plugin.Origin{}, false
	}
	return plugin.Origin{
		ID:          "kpt",
		Name:        "kpt render",
		Regenerates: "kpt fn render",
		Note:        "The next render writes over this file.",
		Instead:     "Set the value through the package's setters, which the pipeline reads.",
	}, true
}
